# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    ports:
      - 26016:26016
    volumes:
    - .docker/mongodb/mongod.conf:/etc/mongod.conf
    - .docker/mongodb/data/db/:/data/db/
    env_file:
      - .env
    command: ["mongod", "-f", "/etc/mongod.conf"]